### ISSUE TITLE
숨고 프로젝트 .dockerignore 개선

### ISSUE THREAD

**Issue by wonjin-dev** [Soomgo-public/docker-study#4]

**Comment by newnickkim** [comment]
현재 숨고 프로젝트는 개발환경에서만 docker가 쓰이고 있으며, 원본 소스를 복사하지 않고 docker bind mounts를 통해 원본 소스 참조를 하고 있는걸로 파악했습니다.

따라서 .dockerignore 파일이 가져다 주는 이점(빌드 컨텍스트 파일 참조 효율성)을 제대로 살리지 못하고 추후 운영 환경에서 docker를 사용하진 않을 것이라 판단하여 따로 .dockerignore 파일을 작성하지 않기로 했습니다.
